### ISSUE TITLE
프로젝트 구조 설계

### ISSUE THREAD

**Issue by jeongjiwoo0522** [OGJG-ZAMONG/ZAMONG-Frontend-V1#6]
## 개요

프로젝트의 코드 아키텍처를 설계해주세요 

## 작업 내용
- [ ] 네 분이서 comment를 달면서 설계방향을 잡아주세요. 
- [ ] 확장성이 있으면 좋겠습니다.
- [ ] 유지보수성이 있게 설계했으면 좋겠습니다.
- [ ] 복잡하다고 주눅들지 않았으면 좋겠습니다. 
- [ ] DSM, Entry 등의 코드를 참고하세요.

**Comment by jcho0216** [comment]
기술 스택을 정해봅시다. 예) React.js + Typescript + Redux or Next.js etc....

**Comment by jcho0216** [comment]
기술스택: React.js + Typescript
